apiVersion: operator.tekton.dev/v1alpha1
kind: TektonResult
metadata:
  name: result
spec:
  targetNamespace: openshift-pipelines
  lokistack_name: logging-loki
  lokistack_namespace: openshift-logging
  auth_disable: true
